spring.application.name=paymentGateway

##Actuartor Config
management.endpoints.web.exposure.include=metrics,health,audit-events
management.endpoint.health.show-details=when_authorized
management.endpoint.health.roles=ROOT

## Config RabbitMQ
spring.rabbitmq.addresses=amqps://aqqazzsp:kkrVzOsPWgrjUF2g1eZjHrwuS1JxihhB@gull.rmq.cloudamqp.com/aqqazzsp
spring.rabbitmq.queue=payments

##Swagger
springdoc.swagger-ui.path=/doc
springdoc.swagger-ui.tagsSorter=alpha

## Webhook ML
base.url.notification.payment=${BASE_URL_NOTIFICATION_PAYMENT}

## Token do Mercado Pago
mercadopago.accessToken=${MERCADOPAGO_ACCESS_TOKEN}
mercadopago.public_key=${MERCADOPAGO_PUBLIC_KEY}

##Envs
BASE_URL_NOTIFICATION_PAYMENT=https://eventpay-back.onrender.com/notificationPay
AMQP_URL=amqps://ghunaulj:Zy2TCicvDVEPFS4DJ15BfVD487ezYppx@jaragua.lmq.cloudamqp.com/ghunaulj
SPRING_RABBITMQ_QUEUE=env-email
MERCADOPAGO_ACCESS_TOKEN=APP_USR-7340758869882424-111015-e83efad91b9898c11c3d239d281bd38a-244807378
MERCADOPAGO_PUBLIC_KEY=APP_USR-de87217c-7d9e-4c63-9d11-75ba42eeaab7

logging.level.org.apache.camel=DEBUG
logging.level.org.springframework.web=DEBUG
